services:
  api:
    build: .
    ports:
      - "8000:8000"
    volumes:
      - .:/app
  queue:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
  worker:
    build: .
    command:
      [
        "watchfiles",
        "--filter",
        "python",
        "python -u app/worker.py",
        "/app/app",
      ]
    volumes:
      - .:/app
